-- Insert Drones
INSERT INTO DRONE (BATTERY_CAPACITY, MODEL, SERIAL_NUMBER, STATE, WEIGHT_LIMIT) VALUES (100, 'LW', 'Drone 1', 'I', 100);
INSERT INTO DRONE (BATTERY_CAPACITY, MODEL, SERIAL_NUMBER, STATE, WEIGHT_LIMIT) VALUES (50, 'LW', 'Drone 2', 'I', 50);
INSERT INTO DRONE (BATTERY_CAPACITY, MODEL, SERIAL_NUMBER, STATE, WEIGHT_LIMIT) VALUES (30, 'MW', 'Drone 3', 'I', 200);
INSERT INTO DRONE (BATTERY_CAPACITY, MODEL, SERIAL_NUMBER, STATE, WEIGHT_LIMIT) VALUES (45, 'MW', 'Drone 4', 'I', 300);
INSERT INTO DRONE (BATTERY_CAPACITY, MODEL, SERIAL_NUMBER, STATE, WEIGHT_LIMIT) VALUES (86, 'CW', 'Drone 5', 'I', 450);
INSERT INTO DRONE (BATTERY_CAPACITY, MODEL, SERIAL_NUMBER, STATE, WEIGHT_LIMIT) VALUES (100, 'HW', 'Drone 6', 'I', 500);
INSERT INTO DRONE (BATTERY_CAPACITY, MODEL, SERIAL_NUMBER, STATE, WEIGHT_LIMIT) VALUES (20, 'MW', 'Drone 7', 'I', 150);
INSERT INTO DRONE (BATTERY_CAPACITY, MODEL, SERIAL_NUMBER, STATE, WEIGHT_LIMIT) VALUES (15, 'MW', 'Drone 8', 'I', 130);
INSERT INTO DRONE (BATTERY_CAPACITY, MODEL, SERIAL_NUMBER, STATE, WEIGHT_LIMIT) VALUES (80, 'CW', 'Drone 9', 'I', 400);
INSERT INTO DRONE (BATTERY_CAPACITY, MODEL, SERIAL_NUMBER, STATE, WEIGHT_LIMIT) VALUES (75, 'HW', 'Drone 10', 'I', 500);

-- Insert Medications
INSERT INTO MEDICATION (CODE, IMAGE, NAME, WEIGHT) VALUES ('CODE_1', 'image', 'MED_1', 10);
INSERT INTO MEDICATION (CODE, IMAGE, NAME, WEIGHT) VALUES ('CODE_2', 'image', 'MED_2', 25);
INSERT INTO MEDICATION (CODE, IMAGE, NAME, WEIGHT) VALUES ('CODE_3', 'image', 'MED_3', 50);
INSERT INTO MEDICATION (CODE, IMAGE, NAME, WEIGHT) VALUES ('CODE_4', 'image', 'MED_4', 60);
INSERT INTO MEDICATION (CODE, IMAGE, NAME, WEIGHT) VALUES ('CODE_5', 'image', 'MED_5', 40);
INSERT INTO MEDICATION (CODE, IMAGE, NAME, WEIGHT) VALUES ('CODE_6', 'image', 'MED_6', 30);
INSERT INTO MEDICATION (CODE, IMAGE, NAME, WEIGHT) VALUES ('CODE_7', 'image', 'MED_7', 42);
INSERT INTO MEDICATION (CODE, IMAGE, NAME, WEIGHT) VALUES ('CODE_8', 'image', 'MED_8', 15);
INSERT INTO MEDICATION (CODE, IMAGE, NAME, WEIGHT) VALUES ('CODE_9', 'image', 'MED_9', 75);
INSERT INTO MEDICATION (CODE, IMAGE, NAME, WEIGHT) VALUES ('CODE_10', 'image', 'MED_10', 3);